In [1]:
import pennylane as qml
from pennylane import numpy as np

In [2]:
dev1 = qml.device("default.qubit", wires=2)

In [3]:
@qml.qnode(dev1)
def circuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.CNOT(wires=[1, 0])
    return qml.probs(wires=[0, 1])

In [6]:
print(circuit([1.1, 2.4]))
#in the output, the probabilities of states |00>, |01>, |10>, |11> are displayed respectively

[0.09543087 0.23732967 0.03587227 0.63136719]


In [7]:
def cost(x):
    return ((circuit(x)[3]+circuit(x)[0])-(circuit(x)[1]+circuit(x)[2]))
    
#the cost function is so defined, such that minimization of the cost function would result in |00>=|11>=0 and |01>=|10>=0.5

In [8]:
init_params = np.array([1.5707, 1.5707]) #initial choice of parameters is randomly taken, which would be updated after each iteration

In [9]:
# initialise the optimizer
opt = qml.GradientDescentOptimizer(stepsize=0.1)

# set the number of steps
steps = 500
# set the initial parameter values
params = init_params

for i in range(steps):
    # update the circuit parameters
    params = opt.step(cost, params)

    if (i + 1) % 5 == 0:
        print("Cost after step {:5d}: {: .7f}".format(i + 1, cost(params)))

print("Optimized rotation angles: {}".format(params)) #this will print the optimized angles, such that |01>=|10>=0.5

Cost after step     5: -0.4665694
Cost after step    10: -0.7706728
Cost after step    15: -0.9128644
Cost after step    20: -0.9686304
Cost after step    25: -0.9889365
Cost after step    30: -0.9961269
Cost after step    35: -0.9986476
Cost after step    40: -0.9995282
Cost after step    45: -0.9998355
Cost after step    50: -0.9999426
Cost after step    55: -0.9999800
Cost after step    60: -0.9999930
Cost after step    65: -0.9999976
Cost after step    70: -0.9999992
Cost after step    75: -0.9999997
Cost after step    80: -0.9999999
Cost after step    85: -1.0000000
Cost after step    90: -1.0000000
Cost after step    95: -1.0000000
Cost after step   100: -1.0000000
Cost after step   105: -1.0000000
Cost after step   110: -1.0000000
Cost after step   115: -1.0000000
Cost after step   120: -1.0000000
Cost after step   125: -1.0000000
Cost after step   130: -1.0000000
Cost after step   135: -1.0000000
Cost after step   140: -1.0000000
Cost after step   145: -1.0000000
Cost after ste

In [10]:
dev = qml.device("default.qubit", wires=2, shots=1, analytic=False)

@qml.qnode(dev)
def circuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.CNOT(wires=[1, 0])
    return qml.probs(wires=[0, 1])

# execute the QNode using 1 shots
result = circuit([3.14159265, 1.5707]) #optimized angles are taken for simulation
result


array([0., 1., 0., 0.])

In [11]:
# execute the QNode again, now using 10 shot
dev.shots = 10
result = circuit([3.14159265, 1.5707]) #optimized angles are taken for simulation
result

array([0. , 0.4, 0.6, 0. ])

In [12]:
# execute the QNode again, now using 100 shot
dev.shots = 100
result = circuit([3.14159265, 1.5707]) #optimized angles are taken for simulation
result

array([0.  , 0.52, 0.48, 0.  ])

In [13]:
# execute the QNode again, now using 1000 shot
dev.shots = 1000
result = circuit([3.14159265, 1.5707]) #optimized angles are taken for simulation
result

array([0.  , 0.53, 0.47, 0.  ])

In [14]:
# execute the QNode again, now using 10000 shot
dev.shots = 10000
result = circuit([3.14159265, 1.5707]) #optimized angles are taken for simulation
result

array([0.    , 0.5005, 0.4995, 0.    ])

In [15]:
# execute the QNode again, now using 100000 shot
dev.shots = 100000
result = circuit([3.14159265, 1.5707]) #optimized angles are taken for simulation
result

array([0.     , 0.50182, 0.49818, 0.     ])

In [17]:
# execute the QNode again, now using 1000000 shot
dev.shots = 1000000
result = circuit([3.14159265, 1.5707])
result

array([0.      , 0.500533, 0.499467, 0.      ])

In [20]:
#It is clear that as the number of shots increases, the accuracy of output increases, such that both |01> and |10> tends to 0.5